### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/gulp-asciidoctor#10]
Hello, could you please release a new version with Asciidoctor 1.5.5-4 ?

Thanks

**Comment by dongwq** [comment]
done.
v1.5.5-4: upgrade asciidoctor.js to version 1.5.5-4 and use version consistent with asciidoctor.js.

**Comment by ggrossetie** [comment]
Thanks :tada:

**Comment by ggrossetie** [comment]
@dongwq I don't know why but the new package is empty: https://registry.npmjs.org/gulp-asciidoctor/-/gulp-asciidoctor-1.5.5-4.tgz

**Comment by dongwq** [comment]
sorry for that. updated npm to the latest and it's done.
