### ISSUE TITLE
New contributor

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/gulp-asciidoctor#14]
@henriette-einstein has expressed interest in maintaining this project. The first task will be to [merge the upgrade to Asciidoctor.js 2+](https://github.com/asciidoctor/gulp-asciidoctor/pull/13) and then publish a new version to npmjs.

@mojavelinux Could you please add him as a contributor? Thanks!

**Comment by mojavelinux** [comment]
Sorry for the delay on this. I've added @Mogztter and @henriette-einstein to the gulp-plugin team, which grants you both admin access. You can then tweak the list of users or the team settings from there.

**Comment by mojavelinux** [comment]
We can close once @henriette-einstein confirms the access has been granted.

**Comment by ghost** [comment]
Hello guys,

the issue can be closed. I have access.

Thanks again for inviting me.

**Comment by mojavelinux** [comment]
That's great. Thanks for pitching in to maintain this project, @henriette-einstein! We're glad to have you.
