### ISSUE TITLE
include:: Syntax Not Working

### ISSUE THREAD

**Issue by craigshoemaker** [asciidoctor/gulp-asciidoctor#5]
When trying to combine separate documents using the [`include::` syntax](http://www.methods.co.nz/asciidoc/userguide.html#X90), instead of getting the contents of the file injected into the generated file, it just generates an anchor linking to the file like this:

``` html
<div class="paragraph">
<p><a href="document1.txt" class="bare">document1.txt</a></p>
</div>
```

Is there a parameter I need to send in to tell the plugin to support includes?

**Comment by dongwq** [comment]
which safe mode are you used? '

**Comment by craigshoemaker** [comment]
Since I wasn't passing in a value, I was just using the default. Here's my `gulpfile.js`:

``` javascript
var gulp = require('gulp');
var watch = require('gulp-watch');
var asciidoctor = require('gulp-asciidoctor');

gulp.task('adoc', function() {

    watch(['./src/*.adoc'], function(){
        gulp.src('./src/*.adoc')
            .pipe(asciidoctor({
                attributes: ['silverlight']
            }))
            .pipe(gulp.dest('./dest'));
    });

});

gulp.task('default', ['adoc']);
```

I'm not sure from the [readme.adoc](https://github.com/dongwq/gulp-asciidoctor/blob/master/readme.adoc) what the argument would be to run it "not in safe mode".

Thanks!

**Comment by mojavelinux** [comment]
I think the build plugins should set the safe mode to unsafe by default to be consistent. The Maven and Gradle plugins do this already.

**Comment by dongwq** [comment]
@mojavelinux  when the save mode is been set to  'unsafe' , two more tests failed.

**Comment by stormbeta** [comment]
This appears to still be an issue, and setting `safe=unsafe` in the gulp attributes didn't help. It still just creates a link instead of actually including the target file.

**Comment by mojavelinux** [comment]
> setting safe=unsafe in the gulp attributes 

That's because the safe mode isn't an attribute, it's an option.

See this test: https://github.com/asciidoctor/gulp-asciidoctor/blob/966cf492abe3430c2512443daa316c901aeb1cd6/test.js#L101-L105

That test needs to be enabled. Then we can be sure the feature works.

**Comment by ghost** [comment]
Pull request #13 will probably solve this issue.

I assume, that the underlying problem was, that relative paths were not handled. Only the base_dir option of AsciiDoctor worked

**Comment by ghost** [comment]
This issue is now fixed and outdated
